In [2]:
!ls

Collaborative_Filtering_Consumer.py  entire_data.csv
Creating_Correlation_matrix.ipynb    run_spark_stream
Output_CF.ipynb			     spark-3.1.1-bin-hadoop2.7
corr_matrix.csv			     temp

In [3]:
!./run_spark_stream

21/06/21 08:36:43 WARN Utils: Your hostname, mlbd resolves to a loopback address: 127.0.1.1; using 10.47.0.5 instead (on interface eth0)
21/06/21 08:36:43 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/root/mlbd_project/Spark_Consumer/spark-3.1.1-bin-hadoop2.7/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
:: loading settings :: url = jar:file:/root/mlbd_project/Spark_Consumer/spark-3.1.1-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-eede2ccb-47f9-4220-a186-2835afb5ecc1;1.0
	confs: [default]
	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.1.1 in central
	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.1.1 in central
	found org.apache.kafka#kafka-clients;2.6.0 in central
	found com.github.luben#zstd-jni;1.4.8-1 in central
	found org.lz4#lz4-java;1.7.1 in central
	found org.xerial.snappy#snappy-java;1.1.8.2 in central
	found org.slf4j#slf4j-api;1.7.30 in central
	found org.spark-project.spark#unused;1.0.0 in central
	found org.apache.commons#commons-pool2;2.6.2 in central
:: resolution report :: resolve 931ms :: artifacts dl 26ms
	:: modules in use:
	com.github.luben#zstd-jni;1.4.8-1 from central in [default]
	org.apache.commons#commons-pool2;2.6.2 from central in [default]
	org.apache.kafka#kafka-clients;2.6.0 from central in [default]
	org.apache.spark#spark-sql-kafka-0-10_2.12;3.1.1 from central in [default]
	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.1.1 from central in [default]
	org.lz4#lz4-java;1.7.1 from central in [default]
	org.slf4j#slf4j-api;1.7.30 from central in [default]
	org.spark-project.spark#unused;1.0.0 from central in [default]
	org.xerial.snappy#snappy-java;1.1.8.2 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   9   |   0   |   0   |   0   ||   9   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-eede2ccb-47f9-4220-a186-2835afb5ecc1
	confs: [default]
	0 artifacts copied, 9 already retrieved (0kB/22ms)
21/06/21 08:36:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Done!     trix -PySpark Structured Streaming with Kafka Application Started ...
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/06/21 08:38:10 INFO SparkContext: Running Spark version 3.1.1
21/06/21 08:38:10 INFO ResourceUtils: ==============================================================
21/06/21 08:38:10 INFO ResourceUtils: No custom resources configured for spark.driver.
21/06/21 08:38:10 INFO ResourceUtils: ==============================================================
21/06/21 08:38:10 INFO SparkContext: Submitted application: MovieRecommendationSystem
21/06/21 08:38:11 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
21/06/21 08:38:11 INFO ResourceProfile: Limiting resource is cpu
21/06/21 08:38:11 INFO ResourceProfileManager: Added ResourceProfile id: 0
21/06/21 08:38:11 INFO SecurityManager: Changing view acls to: root
21/06/21 08:38:11 INFO SecurityManager: Changing modify acls to: root
21/06/21 08:38:11 INFO SecurityManager: Changing view acls groups to:
21/06/21 08:38:11 INFO SecurityManager: Changing modify acls groups to:
21/06/21 08:38:11 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
21/06/21 08:38:11 INFO Utils: Successfully started service 'sparkDriver' on port 34519.
21/06/21 08:38:11 INFO SparkEnv: Registering MapOutputTracker
21/06/21 08:38:11 INFO SparkEnv: Registering BlockManagerMaster
21/06/21 08:38:11 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
21/06/21 08:38:11 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
21/06/21 08:38:11 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
21/06/21 08:38:11 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-8ca70bb0-a3d5-4eae-929f-dd3ec8b8f030
21/06/21 08:38:11 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
21/06/21 08:38:12 INFO SparkEnv: Registering OutputCommitCoordinator
21/06/21 08:38:12 INFO Utils: Successfully started service 'SparkUI' on port 4040.
21/06/21 08:38:12 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.47.0.5:4040
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar at spark://10.47.0.5:34519/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar at spark://10.47.0.5:34519/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/org.apache.kafka_kafka-clients-2.6.0.jar at spark://10.47.0.5:34519/jars/org.apache.kafka_kafka-clients-2.6.0.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/org.apache.commons_commons-pool2-2.6.2.jar at spark://10.47.0.5:34519/jars/org.apache.commons_commons-pool2-2.6.2.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at spark://10.47.0.5:34519/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/com.github.luben_zstd-jni-1.4.8-1.jar at spark://10.47.0.5:34519/jars/com.github.luben_zstd-jni-1.4.8-1.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/org.lz4_lz4-java-1.7.1.jar at spark://10.47.0.5:34519/jars/org.lz4_lz4-java-1.7.1.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar at spark://10.47.0.5:34519/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added JAR file:///root/.ivy2/jars/org.slf4j_slf4j-api-1.7.30.jar at spark://10.47.0.5:34519/jars/org.slf4j_slf4j-api-1.7.30.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar at file:///root/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar
21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar at file:///root/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar
21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/org.apache.kafka_kafka-clients-2.6.0.jar at file:///root/.ivy2/jars/org.apache.kafka_kafka-clients-2.6.0.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/org.apache.kafka_kafka-clients-2.6.0.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.kafka_kafka-clients-2.6.0.jar
21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/org.apache.commons_commons-pool2-2.6.2.jar at file:///root/.ivy2/jars/org.apache.commons_commons-pool2-2.6.2.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/org.apache.commons_commons-pool2-2.6.2.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.commons_commons-pool2-2.6.2.jar

21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at file:///root/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.spark-project.spark_unused-1.0.0.jar
21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/com.github.luben_zstd-jni-1.4.8-1.jar at file:///root/.ivy2/jars/com.github.luben_zstd-jni-1.4.8-1.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/com.github.luben_zstd-jni-1.4.8-1.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/com.github.luben_zstd-jni-1.4.8-1.jar
21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/org.lz4_lz4-java-1.7.1.jar at file:///root/.ivy2/jars/org.lz4_lz4-java-1.7.1.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/org.lz4_lz4-java-1.7.1.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.lz4_lz4-java-1.7.1.jar
21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar at file:///root/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.xerial.snappy_snappy-java-1.1.8.2.jar
21/06/21 08:38:12 INFO SparkContext: Added file file:///root/.ivy2/jars/org.slf4j_slf4j-api-1.7.30.jar at file:///root/.ivy2/jars/org.slf4j_slf4j-api-1.7.30.jar with timestamp 1624264690821
21/06/21 08:38:12 INFO Utils: Copying /root/.ivy2/jars/org.slf4j_slf4j-api-1.7.30.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.slf4j_slf4j-api-1.7.30.jar
21/06/21 08:38:13 INFO Executor: Starting executor ID driver on host 10.47.0.5
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/org.apache.commons_commons-pool2-2.6.2.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/org.apache.commons_commons-pool2-2.6.2.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.commons_commons-pool2-2.6.2.jar
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/org.lz4_lz4-java-1.7.1.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/org.lz4_lz4-java-1.7.1.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.lz4_lz4-java-1.7.1.jar
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/org.apache.kafka_kafka-clients-2.6.0.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/org.apache.kafka_kafka-clients-2.6.0.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.kafka_kafka-clients-2.6.0.jar
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.xerial.snappy_snappy-java-1.1.8.2.jar
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.spark-project.spark_unused-1.0.0.jar
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/com.github.luben_zstd-jni-1.4.8-1.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/com.github.luben_zstd-jni-1.4.8-1.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/com.github.luben_zstd-jni-1.4.8-1.jar
21/06/21 08:38:13 INFO Executor: Fetching file:///root/.ivy2/jars/org.slf4j_slf4j-api-1.7.30.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: /root/.ivy2/jars/org.slf4j_slf4j-api-1.7.30.jar has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.slf4j_slf4j-api-1.7.30.jar
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/org.slf4j_slf4j-api-1.7.30.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO TransportClientFactory: Successfully created connection to /10.47.0.5:34519 after 52 ms (0 ms spent in bootstraps)
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/org.slf4j_slf4j-api-1.7.30.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp9534380954029173266.tmp
21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp9534380954029173266.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.slf4j_slf4j-api-1.7.30.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.slf4j_slf4j-api-1.7.30.jar to class loader
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/org.apache.commons_commons-pool2-2.6.2.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/org.apache.commons_commons-pool2-2.6.2.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp8077764197233540496.tmp
21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp8077764197233540496.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.commons_commons-pool2-2.6.2.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.commons_commons-pool2-2.6.2.jar to class loader
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/org.lz4_lz4-java-1.7.1.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/org.lz4_lz4-java-1.7.1.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp17255763478021022280.tmp
21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp17255763478021022280.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.lz4_lz4-java-1.7.1.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.lz4_lz4-java-1.7.1.jar to class loader
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp18005270344319568852.tmp
21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp18005270344319568852.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.1.jar to class loader
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp667876368332753714.tmp

21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp667876368332753714.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.xerial.snappy_snappy-java-1.1.8.2.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.xerial.snappy_snappy-java-1.1.8.2.jar to class loader
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/org.apache.kafka_kafka-clients-2.6.0.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/org.apache.kafka_kafka-clients-2.6.0.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp4169833024125793159.tmp
21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp4169833024125793159.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.kafka_kafka-clients-2.6.0.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.kafka_kafka-clients-2.6.0.jar to class loader
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp4486107445873828175.tmp
21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp4486107445873828175.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.1.jar to class loader
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/com.github.luben_zstd-jni-1.4.8-1.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/com.github.luben_zstd-jni-1.4.8-1.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp18340587084350630757.tmp
21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp18340587084350630757.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/com.github.luben_zstd-jni-1.4.8-1.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/com.github.luben_zstd-jni-1.4.8-1.jar to class loader
21/06/21 08:38:13 INFO Executor: Fetching spark://10.47.0.5:34519/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1624264690821
21/06/21 08:38:13 INFO Utils: Fetching spark://10.47.0.5:34519/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp9759863399426687338.tmp
21/06/21 08:38:13 INFO Utils: /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/fetchFileTemp9759863399426687338.tmp has been previously copied to /tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.spark-project.spark_unused-1.0.0.jar
21/06/21 08:38:13 INFO Executor: Adding file:/tmp/spark-bc366a50-ee8a-4cee-9a97-fc3499ff779e/userFiles-d9e383af-5694-4d34-bd15-f31ae50b2de5/org.spark-project.spark_unused-1.0.0.jar to class loader
21/06/21 08:38:13 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46293.
21/06/21 08:38:13 INFO NettyBlockTransferService: Server created on 10.47.0.5:46293
21/06/21 08:38:13 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
21/06/21 08:38:13 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.47.0.5, 46293, None)
21/06/21 08:38:13 INFO BlockManagerMasterEndpoint: Registering block manager 10.47.0.5:46293 with 434.4 MiB RAM, BlockManagerId(driver, 10.47.0.5, 46293, None)
21/06/21 08:38:13 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.47.0.5, 46293, None)
21/06/21 08:38:13 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.47.0.5, 46293, None)
21/06/21 08:38:14 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/root/mlbd_project/Spark_Consumer/spark-warehouse').
21/06/21 08:38:14 INFO SharedState: Warehouse path is 'file:/root/mlbd_project/Spark_Consumer/spark-warehouse'.
 kafka Started ...
Printing Schema of transaction_detail_df:
root
 |-- value: string (nullable = true)
 |-- timestamp: string (nullable = true)

Showing Recommendations for Batch Number 0
-------------------------------------------
Batch: 0
-------------------------------------------
+-------+-----+------+------+------+
|movieId|title|genres|userId|rating|
+-------+-----+------+------+------+
+-------+-----+------+------+------+

Showing Recommendations for Batch Number 1
-------------------------------------------
Batch: 1
-------------------------------------------
Recommendation for user no. 50
+-------+---------------------------+--------------------------+------+------+
|movieId|title                      |genres                    |userId|rating|
+-------+---------------------------+--------------------------+------+------+
|6888   |Scary Movie 3 (2003)       |Comedy Horror             |232   |3.0   |
|95508  |Cleanskin (2012)           |Crime Drama Thriller      |448   |3.5   |
|5418   |Bourne Identity, The (2002)|Action Mystery Thriller   |325   |4.0   |
|2164   |Surf Nazis Must Die (1987) |Action Comedy Drama Horror|50    |1.0   |
+-------+---------------------------+--------------------------+------+------+

Star Wars: Episode IV - A New Hope (1977)                0.049091
Jurassic Park (1993)                                     0.046676
Braveheart (1995)                                        0.046326
Terminator 2: Judgment Day (1991)                        0.044438
Schindler's List (1993)                                  0.043866
Star Wars: Episode V - The Empire Strikes Back (1980)    0.042918
Usual Suspects, The (1995)                               0.041979
American Beauty (1999)                                   0.041353
Seven (a.k.a. Se7en) (1995)                              0.041301
Apollo 13 (1995)                                         0.041057
dtype: float64
Recommendation for user no. 232
Scary Movie 2 (2001)                      0.318604
Scary Movie 4 (2006)                      0.280579
Daddy Day Care (2003)                     0.259397
Casino Jack (2010)                        0.237709
Rundown, The (2003)                       0.237658
National Security (2003)                  0.233319
S.W.A.T. (2003)                           0.226364
Cats & Dogs (2001)                        0.224640
Impossible, The (Imposible, Lo) (2012)    0.222270
xXx (2002)                                0.219495
dtype: float64
Recommendation for user no. 325
Bourne Supremacy, The (2004)    1.025139
Bourne Ultimatum, The (2007)    0.887978
Ocean's Eleven (2001)           0.868227
Casino Royale (2006)            0.813083
Minority Report (2002)          0.806347
Spider-Man (2002)               0.786710
Catch Me If You Can (2002)      0.770197
I, Robot (2004)                 0.741084
Italian Job, The (2003)         0.733728
Gladiator (2000)                0.733584
dtype: float64
Recommendation for user no. 448

Dad's Army (1971)                        1.0
Dark Places (2015)                       1.0
Carnival Magic (1981)                    1.0
Cherrybomb (2009)                        1.0
Sex Ed (2014)                            1.0
42 (2013)                                1.0
Railway Children, The (1970)             1.0
Barney's Version (2010)                  1.0
Seve (2014)                              1.0
Sessions, The (Surrogate, The) (2012)    1.0
dtype: float64
Showing Recommendations for Batch Number 2
-------------------------------------------
Batch: 2
-------------------------------------------
+-------+------------------------------+-----------------------------+------+------+
|movieId|title                         |genres                       |userId|rating|
+-------+------------------------------+-----------------------------+------+------+
|4299   |Knight's Tale, A (2001)       |Action Comedy Romance        |483   |3.0   |
|60126  |Get Smart (2008)              |Action Comedy                |73    |3.5   |
|3741   |Badlands (1973)               |Crime Drama Thriller         |275   |5.0   |
|303    |Quick and the Dead, The (1995)|Action Thriller Western      |274   |4.0   |
|2313   |Elephant Man, The (1980)      |Drama                        |469   |4.0   |
|68237  |Moon (2009)                   |Drama Mystery Sci-Fi Thriller|279   |4.5   |
+-------+------------------------------+-----------------------------+------+------+

Recommendation for user no. 73
Green Lantern (2011)                                0.560731
This Means War (2012)                               0.552545
National Treasure (2004)                            0.500044
National Treasure: Book of Secrets (2007)           0.499719
Switch, The (2010)                                  0.474528
Jonah Hex (2010)                                    0.473911
Here Comes the Boom (2012)                          0.468687
Total Recall (2012)                                 0.467129
Seeking a Friend for the End of the World (2012)    0.466967
Boondock Saints II: All Saints Day, The (2009)      0.462419
dtype: float64
Recommendation for user no. 274
Another Stakeout (1993)      0.676559
Perfect Score, The (2004)    0.586161
Drag Me to Hell (2009)       0.576137
Tears of the Sun (2003)      0.572678
Eight Below (2006)           0.572380
Major League (1989)          0.563017
Duck, You Sucker (1971)      0.551979
Snakes on a Plane (2006)     0.549041
S.W.A.T. (2003)              0.547789
Wicker Park (2004)           0.540777
dtype: float64
Recommendation for user no. 275
Hands on a Hard Body (1996)                      1.215011
Cruise, The (1998)                               1.208032
Richard Pryor Live on the Sunset Strip (1982)    1.194650
Flirting (1991)                                  1.157612
Two Jakes, The (1990)                            1.076946
Heavy (1995)                                     1.065218
Decline of Western Civilization, The (1981)      1.026754
Palm Beach Story, The (1942)                     0.997645
Ulee's Gold (1997)                               0.976916
Chinatown (1974)                                 0.967733
dtype: float64
Recommendation for user no. 279
The Hateful Eight (2015)         0.971226
Fantastic Mr. Fox (2009)         0.967780
Seven Psychopaths (2012)         0.964702
World's End, The (2013)          0.948943
In Bruges (2008)                 0.948269
Nightcrawler (2014)              0.922068
District 9 (2009)                0.914887
Kick-Ass (2010)                  0.909265
Adjustment Bureau, The (2011)    0.906237
Drive (2011)                     0.890606
dtype: float64
Recommendation for user no. 469
Outsiders, The (1983)                                       0.680557
Pee-wee's Big Adventure (1985)                              0.667649
Christmas Carol, A (1938)                                   0.658509
Earth Girls Are Easy (1988)                                 0.649965
Manhattan Project, The (1986)                               0.639026
Barbarian Invasions, The (Les invasions barbares) (2003)    0.632441
Moonlight Mile (2002)                                       0.630975
Sweet Sixteen (2002)                                        0.629367
Son's Room, The (Stanza del figlio, La) (2001)              0.625058
Volver (2006)                                               0.620503
dtype: float64
Recommendation for user no. 483
Lara Croft: Tomb Raider (2001)                                                                    0.236804
Van Helsing (2004)                                                                                0.226296
Fast and the Furious, The (2001)                                                                  0.224725
Whole Nine Yards, The (2000)                                                                      0.222086
Miss Congeniality (2000)                                                                          0.219567
Die Another Day (2002)                                                                            0.216891
Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)    0.216100
American Pie 2 (2001)                                                                             0.215418
Jay and Silent Bob Strike Back (2001)                                                             0.210794
Emperor's New Groove, The (2000)                                                                  0.210384
dtype: float64
Showing Recommendations for Batch Number 3
-------------------------------------------
Batch: 3
-------------------------------------------
+-------+-------------------------+-----------------------+------+------+
|movieId|title                    |genres                 |userId|rating|
+-------+-------------------------+-----------------------+------+------+
|5004   |Party, The (1968)        |Comedy                 |50    |3.0   |
|3752   |Me, Myself & Irene (2000)|Adventure Comedy       |480   |3.5   |
|355    |Flintstones, The (1994)  |Children Comedy Fantasy|599   |1.0   |
+-------+-------------------------+-----------------------+------+------+

Recommendation for user no. 50
Moscow on the Hudson (1984)                                         0.316754
Damsels in Distress (2011)                                          0.274366
Millennium Actress (Sennen joyû) (2001)                             0.268930
That Obscure Object of Desire (Cet obscur objet du désir) (1977)    0.267892
Black Christmas (1974)                                              0.266568
Adventures of Baron Munchausen, The (1988)                          0.265930
General, The (1998)                                                 0.263836
Belle époque (1992)                                                 0.263836
Any Which Way You Can (1980)                                        0.263836
Pierrot le fou (1965)                                               0.249308
dtype: float64
Recommendation for user no. 480
Road Trip (2000)                           0.560968
Scary Movie (2000)                         0.464002
Evolution (2001)                           0.446089
Zoolander (2001)                           0.438905
Dodgeball: A True Underdog Story (2004)    0.428682
Kingpin (1996)                             0.415310
Orange County (2002)                       0.410179
Man on the Moon (1999)                     0.408466
Bedazzled (2000)                           0.405970
Score, The (2001)                          0.401137
dtype: float64
Recommendation for user no. 599
Lives of Others, The (Das leben der Anderen) (2006)                                                     0.072172
Now You See Me (2013)                                                                                   0.068293
Downfall (Untergang, Der) (2004)                                                                        0.067264
Lone Star (1996)                                                                                        0.065654
Nightcrawler (2014)                                                                                     0.064949
I Am Sam (2001)                                                                                         0.061437
Prisoners (2013)                                                                                        0.060207
American Wedding (American Pie 3) (2003)                                                                0.059506
Bicycle Thieves (a.k.a. The Bicycle Thief) (a.k.a. The Bicycle Thieves) (Ladri di biciclette) (1948)    0.059454
Dead Man (1995)                                                                                         0.057793
dtype: float64

^C
Traceback (most recent call last):
  File "/root/mlbd_project/Spark_Consumer/Collaborative_Filtering_Consumer.py", line 103, in <module>
    my_df.awaitTermination()
  File "/root/mlbd_project/Spark_Consumer/spark-3.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/streaming.py", line 101, in awaitTermination
  File "/root/mlbd_project/Spark_Consumer/spark-3.1.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1303, in __call__
  File "/root/mlbd_project/Spark_Consumer/spark-3.1.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1033, in send_command
  File "/root/mlbd_project/Spark_Consumer/spark-3.1.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1200, in send_command
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/root/mlbd_project/Spark_Consumer/spark-3.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/context.py", line 285, in signal_handler
KeyboardInterrupt

In [37]:
import pandas 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
df = pandas.read_csv('entire_data.csv')
df.head()

,Unnamed: 0,movieId,title,genres,userId,rating
0,0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,1,4.0
1,1,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,5,4.0
2,2,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,7,4.5
3,3,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,15,2.5
4,4,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,17,4.5

In [50]:
df.shape

(100836, 6)

In [51]:
df = df.sample(n = 10000)

In [52]:
df.head()

,Unnamed: 0,movieId,title,genres,userId,rating
13520,13520,495,In the Realm of the Senses (Ai no corrida) (1976),Drama,603,5.0
76314,76314,8529,"Terminal, The (2004)",Comedy Drama Romance,438,2.0
46141,46141,2657,"Rocky Horror Picture Show, The (1975)",Comedy Horror Musical Sci-Fi,20,5.0
83743,83743,48780,"Prestige, The (2006)",Drama Mystery Sci-Fi Thriller,105,5.0
98333,98333,122912,Avengers: Infinity War - Part I (2018),Action Adventure Sci-Fi,305,4.5

In [53]:
df = df[['movieId','title','genres','userId','rating']]
df.head()

,movieId,title,genres,userId,rating
13520,495,In the Realm of the Senses (Ai no corrida) (1976),Drama,603,5.0
76314,8529,"Terminal, The (2004)",Comedy Drama Romance,438,2.0
46141,2657,"Rocky Horror Picture Show, The (1975)",Comedy Horror Musical Sci-Fi,20,5.0
83743,48780,"Prestige, The (2006)",Drama Mystery Sci-Fi Thriller,105,5.0
98333,122912,Avengers: Infinity War - Part I (2018),Action Adventure Sci-Fi,305,4.5

In [55]:
df.to_csv('streaming_data.csv')

In [47]:
features = ['genres']

# Create a column in DF which combines all selected features
for feature in features:
    df[feature] = df[feature].fillna('')

def combine_features(row):
    try:
        return row["genres"]
    except:
        print("Error:", row)

df["combined_features"] = df.apply(combine_features,axis=1)

<ipython-input-47-8d026e02efc9>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature] = df[feature].fillna('')

In [48]:
df.head()

,movieId,title,genres,userId,rating,combined_features
14989,553,Tombstone (1993),Action Drama Western,32,3.0,Action Drama Western
97574,115203,"Culture High, The (2014)",Documentary,50,3.0,Documentary
81563,41569,King Kong (2005),Action Adventure Drama Fantasy Thriller,534,4.0,Action Adventure Drama Fantasy Thriller
62752,4621,Look Who's Talking (1989),Comedy Romance,100,4.0,Comedy Romance
570,7,Sabrina (1995),Comedy Romance,411,3.0,Comedy Romance

In [27]:
df.shape

(1000, 7)

In [28]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])

In [29]:
count_matrix

<1000x21 sparse matrix of type '<class 'numpy.int64'>'
	with 3019 stored elements in Compressed Sparse Row format>

In [30]:
cosine_sim = cosine_similarity(count_matrix)

In [31]:
cosine_sim.shape

(1000, 1000)

In [32]:
cosine_sim

array([[1.        , 0.40824829, 0.        , ..., 0.33333333, 0.        ,
        0.        ],
       [0.40824829, 1.        , 0.35355339, ..., 0.61237244, 0.        ,
        0.20412415],
       [0.        , 0.35355339, 1.        , ..., 0.57735027, 0.        ,
        0.57735027],
       ...,
       [0.33333333, 0.61237244, 0.57735027, ..., 1.        , 0.        ,
        0.33333333],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.57735027],
       [0.        , 0.20412415, 0.57735027, ..., 0.33333333, 0.57735027,
        1.        ]])

In [19]:
movieIndices = df[['movieId']]
movieIndices.head()

       movieId
47558     2745
94909    97225
21716     1010
67095     5437
7195       265

In [36]:
for movieIndex in zip(df['userId'],df['movieId']):
    print(movieIndex)

(592, 95)
(432, 79132)
(489, 337)
(181, 533)
(45, 2707)
(322, 44555)
(275, 1219)
(305, 56801)
(602, 647)
(4, 417)
(57, 1278)
(98, 79139)
(51, 4262)
(140, 5620)
(28, 5445)
(222, 32587)
(474, 2745)
(209, 96079)
(155, 1302)
(415, 3717)
(326, 2329)
(255, 1907)
(432, 589)
(372, 1358)
(561, 1089)
(187, 745)
(68, 6193)
(608, 2291)
(586, 3175)
(610, 122922)
(288, 2641)
(330, 5418)
(462, 2243)
(305, 2329)
(234, 2571)
(444, 344)
(555, 3441)
(525, 6807)
(477, 5291)
(522, 296)
(15, 68237)
(562, 1527)
(368, 2490)
(517, 49274)
(524, 454)
(460, 48738)
(277, 836)
(307, 54785)
(171, 1073)
(24, 1663)
(122, 115617)
(360, 1597)
(580, 3702)
(414, 112)
(591, 3615)
(482, 2640)
(182, 3409)
(600, 2718)
(317, 3160)
(525, 3000)
(179, 3)
(414, 137857)
(12, 830)
(4, 492)
(21, 1918)
(563, 62718)
(387, 5065)
(365, 260)
(599, 88129)
(525, 3977)
(256, 453)
(292, 541)
(603, 4789)
(111, 4262)
(14, 508)
(559, 273)
(339, 8368)
(387, 2901)
(600, 6502)
(325, 4034)
(610, 33683)
(570, 10)
(318, 377)
(14, 367)
(89, 147410)
(182, 3481)
(414, 1917)
(199, 1287)
(184, 189333)
(114, 54001)
(283, 110)
(438, 6709)
(600, 2470)
(599, 3962)
(438, 5401)
(230, 2985)
(43, 292)
(292, 1097)
(404, 141)
(410, 3362)
(564, 128520)
(332, 431)
(288, 53519)
(420, 3081)
(387, 4065)
(198, 1619)
(474, 1367)
(274, 661)
(279, 71535)
(187, 1339)
(50, 170875)
(274, 27592)
(140, 8982)
(273, 590)
(349, 586)
(318, 143859)
(365, 3996)
(84, 948)
(288, 2367)
(500, 2108)
(213, 8957)
(419, 8641)
(599, 1753)
(255, 1663)
(156, 185)
(6, 477)
(305, 49347)
(177, 78499)
(156, 3504)
(532, 517)
(171, 1193)
(380, 3798)
(275, 441)
(477, 2694)
(6, 8)
(282, 4017)
(103, 57522)
(603, 1955)
(328, 44191)
(385, 247)
(137, 968)
(226, 356)
(132, 3489)
(429, 266)
(560, 1884)
(57, 224)
(255, 2355)
(179, 367)
(448, 91273)
(19, 733)
(414, 106916)
(405, 26258)
(606, 6140)
(580, 3551)
(562, 99191)
(387, 1197)
(249, 185435)
(19, 2123)
(144, 778)
(371, 112512)
(48, 1193)
(219, 33646)
(414, 1997)
(414, 68157)
(177, 117881)
(346, 6711)
(602, 172)
(372, 357)
(560, 3489)
(251, 1259)
(198, 58)
(294, 2796)
(312, 5421)
(63, 1527)
(55, 2763)
(380, 141544)
(167, 586)
(564, 102903)
(608, 379)
(561, 4121)
(606, 3791)
(274, 4149)
(441, 208)
(232, 43928)
(109, 11)
(274, 69844)
(72, 1270)
(380, 410)
(38, 595)
(257, 494)
(543, 6482)
(405, 5810)
(590, 4011)
(391, 1527)
(483, 480)
(307, 6709)
(57, 1080)
(177, 6377)
(452, 2916)
(586, 81845)
(462, 1246)
(232, 4993)
(274, 8910)
(41, 3408)
(217, 1374)
(98, 97921)
(128, 1196)
(489, 357)
(19, 2668)
(599, 2356)
(68, 8677)
(525, 3578)
(98, 4720)
(233, 72998)
(71, 62)
(414, 799)
(74, 858)
(534, 1721)
(578, 56389)
(91, 1225)
(592, 788)
(608, 45499)
(371, 55167)
(313, 1212)
(158, 55391)
(122, 103228)
(489, 2001)
(599, 8169)
(552, 1970)
(603, 1860)
(599, 6947)
(51, 2724)
(599, 65)
(137, 7001)
(179, 377)
(608, 153)
(356, 3052)
(104, 4476)
(599, 1245)
(517, 1997)
(599, 3861)
(111, 71838)
(227, 31410)
(250, 3418)
(610, 102123)
(200, 40819)
(113, 1944)
(525, 5791)
(599, 7366)
(122, 8807)
(377, 62383)
(464, 32)
(310, 2944)
(462, 3425)
(380, 3986)
(19, 3837)
(105, 95377)
(362, 48780)
(249, 8917)
(18, 1247)
(365, 5299)
(600, 440)
(425, 3977)
(441, 2683)
(38, 497)
(246, 60069)
(452, 2700)
(357, 1380)
(474, 7137)
(480, 46970)
(414, 72378)
(484, 4388)
(405, 4624)
(580, 3698)
(27, 1588)
(52, 73017)
(140, 1240)
(288, 3525)
(448, 99415)
(68, 2078)
(44, 1405)
(522, 2571)
(599, 8045)
(274, 58025)
(220, 60069)
(484, 4914)
(525, 1022)
(274, 60538)
(493, 2640)
(555, 913)
(103, 7438)
(606, 8623)
(198, 2184)
(310, 2683)
(73, 88140)
(274, 4105)
(332, 2917)
(594, 990)
(294, 500)
(474, 2517)
(483, 1088)
(305, 89118)
(223, 595)
(153, 2291)
(428, 3744)
(511, 96737)
(177, 3159)
(202, 2147)
(606, 6989)
(474, 5247)
(81, 367)
(217, 2054)
(84, 1228)
(91, 316)
(474, 351)
(290, 1699)
(307, 6827)
(607, 2699)
(448, 143859)
(552, 1912)
(305, 80489)
(422, 5004)
(286, 778)
(525, 39)
(195, 908)
(156, 6297)
(219, 8972)
(265, 1727)
(275, 1466)
(477, 5378)
(219, 4025)
(312, 2393)
(232, 4370)
(298, 3702)
(82, 6953)
(68, 3825)
(64, 4246)
(190, 7323)
(160, 2094)
(33, 2875)
(571, 1980)
(125, 108727)
(474, 909)
(51, 2402)
(606, 3462)
(325, 3927)
(384, 1258)
(179, 339)
(294, 3424)
(580, 2745)
(274, 842)
(109, 266)
(606, 3824)
(226, 780)
(328, 54286)
(318, 58162)
(357, 4848)
(380, 73017)
(62, 115680)
(45, 648)
(94, 588)
(376, 780)
(253, 66371)
(326, 1619)
(151, 719)
(167, 45722)
(414, 91542)
(307, 531)
(91, 799)
(606, 3676)
(387, 1208)
(304, 457)
(438, 145)
(19, 490)
(438, 95)
(524, 442)
(328, 60069)
(385, 1080)
(233, 58559)
(19, 2153)
(470, 292)
(33, 43)
(347, 32)
(525, 2571)
(590, 5679)
(129, 6711)
(19, 316)
(249, 39446)
(28, 55721)
(204, 70286)
(288, 48414)
(476, 595)
(274, 54785)
(1, 1060)
(139, 99114)
(113, 1086)
(282, 30749)
(268, 2641)
(603, 4784)
(90, 1046)
(311, 5992)
(44, 1552)
(187, 4034)
(608, 2174)
(115, 3052)
(305, 56367)
(219, 4446)
(489, 5541)
(590, 33615)
(140, 6787)
(528, 51037)
(606, 2065)
(66, 5574)
(285, 3481)
(414, 3784)
(414, 5325)
(182, 1060)
(380, 2115)
(596, 3535)
(288, 2359)
(34, 3793)
(372, 1079)
(46, 316)
(559, 265)
(129, 3556)
(111, 102903)
(63, 4995)
(561, 101864)
(157, 3174)
(107, 62)
(517, 1702)
(448, 93982)
(136, 367)
(500, 1910)
(381, 45722)
(462, 53996)
(520, 2011)
(133, 457)
(91, 2657)
(474, 7162)
(308, 92259)
(52, 47099)
(603, 4855)
(606, 3822)
(140, 3363)
(561, 4776)
(599, 431)
(282, 3949)
(606, 5218)
(555, 1614)
(436, 362)
(607, 3114)
(291, 72998)
(560, 1704)
(286, 4993)
(554, 170)
(470, 786)
(352, 6539)
(117, 160)
(274, 1917)
(455, 377)
(342, 2724)
(119, 7458)
(432, 49272)
(462, 1089)
(599, 2301)
(114, 4306)
(27, 808)
(43, 350)
(406, 2694)
(325, 2239)
(246, 356)
(391, 750)
(274, 2078)
(453, 2329)
(135, 4037)
(339, 56174)
(274, 5879)
(352, 116823)
(393, 4022)
(559, 836)
(249, 786)
(200, 50601)
(610, 919)
(19, 497)
(140, 7161)
(68, 122904)
(132, 4306)
(391, 5417)
(560, 88129)
(594, 4823)
(169, 1088)
(600, 1285)
(307, 38038)
(313, 2657)
(340, 110)
(47, 6765)
(52, 48516)
(288, 1210)
(304, 1566)
(380, 1047)
(298, 5971)
(357, 2011)
(495, 7458)
(167, 2083)
(392, 1221)
(187, 2318)
(380, 34143)
(599, 26585)
(414, 8638)
(414, 4235)
(599, 122916)
(610, 8910)
(351, 6263)
(586, 134130)
(226, 5679)
(381, 6297)
(68, 2728)
(480, 2572)
(217, 2058)
(326, 71462)
(89, 104)
(405, 8798)
(156, 2064)
(95, 1529)
(313, 3081)
(298, 67734)
(414, 5618)
(608, 8368)
(474, 52975)
(50, 113374)
(21, 111743)
(331, 4963)
(448, 1920)
(605, 380)
(305, 1240)
(586, 102445)
(432, 1892)
(244, 2916)
(88, 223)
(599, 544)
(186, 1193)
(286, 6539)
(221, 1233)
(489, 431)
(306, 97225)
(599, 3243)
(249, 143355)
(181, 437)
(140, 2571)
(474, 34542)
(599, 36519)
(111, 59022)
(474, 4105)
(221, 3702)
(160, 3301)
(608, 5630)
(483, 54001)
(122, 2692)
(98, 608)
(15, 94864)
(380, 88744)
(47, 30812)
(174, 420)
(45, 3196)
(313, 4571)
(606, 2436)
(221, 1356)
(263, 988)
(266, 1198)
(142, 367)
(450, 1544)
(153, 1028)
(414, 1610)
(230, 45722)
(573, 1198)
(610, 130052)
(144, 3408)
(564, 37384)
(573, 8783)
(610, 79057)
(195, 2880)
(246, 60937)
(406, 1282)
(144, 8360)
(356, 104)
(62, 101864)
(474, 6869)
(448, 78041)
(32, 648)
(233, 3081)
(58, 32)
(567, 184253)
(597, 1527)
(496, 720)
(480, 48385)
(298, 73266)
(280, 7669)
(42, 2001)
(332, 1)
(167, 7842)
(226, 3087)
(298, 70641)
(143, 40962)
(57, 3258)
(334, 5952)
(122, 8464)
(599, 81834)
(474, 1148)
(361, 466)
(600, 2946)
(474, 5325)
(414, 49910)
(469, 1747)
(599, 112556)
(489, 87232)
(387, 154)
(610, 95858)
(8, 454)
(380, 173)
(305, 904)
(456, 786)
(474, 247)
(318, 8724)
(448, 6212)
(477, 2700)
(377, 32)
(133, 288)
(372, 1198)
(448, 1391)
(339, 55247)
(414, 2089)
(57, 1620)
(432, 5952)
(367, 1246)
(546, 1270)
(567, 135887)
(105, 5026)
(587, 1230)
(414, 5256)
(82, 170)
(354, 353)
(474, 3498)
(21, 3000)
(217, 1777)
(414, 7347)
(500, 440)
(186, 1198)
(434, 2706)
(477, 1556)
(313, 4210)
(135, 410)
(314, 485)
(414, 5635)
(427, 5449)
(310, 2372)
(599, 2990)
(125, 95167)
(256, 103228)
(23, 1206)
(318, 56607)
(223, 1285)
(596, 179401)
(387, 1210)
(135, 1)
(270, 1356)
(105, 26903)
(474, 39292)
(92, 2085)
(489, 1333)
(19, 1882)
(339, 1527)
(438, 21)
(610, 80094)
(182, 34048)
(610, 4306)
(414, 2169)
(599, 3045)
(62, 185135)
(606, 31923)
(131, 1228)
(187, 7099)
(298, 8636)
(418, 156387)
(305, 8529)
(330, 589)
(226, 51255)
(522, 1198)
(560, 6041)
(140, 36529)
(18, 367)
(606, 8636)
(365, 113453)
(4, 232)
(546, 1544)
(288, 1262)
(325, 5075)
(424, 3535)
(153, 1580)
(414, 2808)
(561, 54286)
(448, 3030)
(573, 53972)
(552, 2428)
(484, 160)
(249, 4886)
(432, 5108)
(274, 172)
(244, 1785)
(330, 1213)
(484, 6281)
(246, 8254)
(182, 2694)
(480, 1080)
(414, 5264)
(174, 339)
(596, 4973)
(6, 46)
(389, 788)
(534, 3793)
(509, 50796)
(305, 93805)
(414, 2003)
(607, 366)
(514, 2571)
(474, 6380)
(368, 3704)
(606, 4673)
(144, 480)
(411, 111)
(442, 1272)
(563, 80241)
(428, 1552)
(555, 3527)
(50, 2732)
(577, 2366)
(41, 3948)
(306, 6377)
(249, 1086)
(298, 1228)
(43, 590)
(610, 54259)
(28, 8378)
(288, 661)
(135, 2387)
(294, 2006)
(426, 5989)
(335, 762)
(586, 1073)
(448, 103221)
(393, 111362)
(361, 2700)
(608, 8636)
(328, 2329)
(125, 69516)
(305, 122900)
(82, 3703)
(381, 78105)
(573, 8528)
(448, 1620)
(495, 1208)
(351, 5952)
(566, 551)
(328, 5989)
(436, 250)
(414, 5437)
(95, 6979)
(590, 910)
(177, 736)
(186, 1301)
(187, 1690)
(365, 2716)
(382, 1003)
(599, 543)
(466, 5459)
(608, 4487)
(51, 2762)
(605, 4639)
(140, 146)
(182, 475)
(239, 590)
(97, 3717)
(606, 4896)
(438, 4887)
(313, 1603)
(280, 7)
(222, 68954)
(85, 1140)
(274, 1499)
(298, 68157)
(555, 3175)
(59, 1580)
(376, 3089)
(493, 1214)
(186, 593)
(597, 1955)
(352, 54259)
(216, 921)
(182, 5312)
(68, 4890)
(425, 2355)
(28, 6281)
(432, 3717)
(314, 748)
(323, 551)
(610, 4388)
(600, 673)
(105, 6643)
(469, 2054)
(182, 3476)
(62, 58559)
(497, 2324)
(74, 6244)
(6, 337)
(19, 1862)
(108, 5135)
(608, 253)
(21, 86068)
(249, 3994)
(288, 1954)
(232, 49220)
(599, 6582)
(307, 3468)
(418, 6863)
(189, 2762)
(414, 60128)
(64, 7360)
(514, 1270)
(83, 2858)
(571, 1350)
(125, 26680)
(84, 1285)
(380, 49278)
(560, 59037)
(508, 1175)
(21, 2949)
(36, 1376)
(17, 1209)
(414, 96821)
(517, 2142)
(282, 2571)
(352, 106002)
(199, 1797)
(84, 299)
(287, 5952)
(357, 524)
(600, 5952)
(357, 26133)
(414, 257)
(160, 93)
(610, 3744)
(552, 780)
(64, 32)
(274, 44972)
(230, 2115)
(355, 1721)
(330, 2140)
(573, 3213)
(586, 1485)
(241, 7361)
(263, 8366)
(90, 17)
(64, 1580)
(288, 1015)
(560, 2012)
(68, 1499)
(256, 33004)
(512, 587)
(603, 3102)
(73, 33495)
(232, 43679)
(573, 4776)
(8, 236)
(177, 81591)
(484, 1777)
(495, 4776)
(428, 2459)
(288, 3317)
(495, 33166)
(103, 7153)
(305, 60069)
(328, 81845)
(348, 3083)
(608, 924)
(425, 1047)
(102, 592)
(381, 34319)
(561, 89745)
(428, 4446)
(144, 163)
(265, 589)
(365, 8644)
(468, 161)
(561, 923)
(525, 72226)
(159, 1197)
(414, 36519)
(21, 117851)
(44, 663)
(265, 608)
(590, 1234)
(474, 1010)
(217, 1587)
(164, 1580)
(352, 67197)
(201, 2011)
(610, 107406)
(230, 35836)
(15, 2916)
(129, 4025)
(169, 150)
(313, 2530)
(599, 4718)
(590, 1517)
(169, 4193)
(380, 5507)
(372, 1275)
(51, 4344)
(63, 106487)
(567, 2138)
(209, 2028)
(448, 7143)
(155, 3114)
(573, 1)
(6, 524)
(132, 3717)
(292, 31221)
(599, 20)
(469, 1247)
(424, 3176)
(382, 63082)
(62, 8914)
(328, 2717)
(610, 4794)
(442, 2145)
(279, 55363)
(288, 2176)
(593, 8784)
(599, 7720)
(186, 1210)
(474, 1223)
(52, 58559)
(91, 3681)
(160, 1909)
(448, 2383)
(534, 104243)
(132, 30749)
(514, 1975)
(177, 42002)
(64, 3114)
(414, 143355)
(465, 1834)
(50, 190183)
(580, 44022)
(603, 3265)
(135, 4553)
(68, 71282)
(18, 1729)
(438, 4734)
(140, 8798)
(430, 3793)
(307, 8636)
(558, 3274)
(524, 780)
(198, 1213)
(555, 2672)
(524, 1233)
(597, 2014)
(212, 55247)
(152, 541)
(601, 177765)
(156, 2352)
(509, 7444)
(103, 524)
(292, 83613)
(414, 75)
(292, 480)
(339, 4262)
(266, 2321)
(282, 10)
(20, 1032)
(434, 2174)
(239, 55820)
(587, 1641)
(484, 203)
(292, 161)
(305, 69275)
(418, 3438)
(474, 1293)
(219, 1953)
(179, 165)
(599, 4619)
(599, 27831)
(428, 2890)
(567, 71530)
(606, 500)
(447, 165)
(305, 1729)
(469, 2736)
(555, 1542)